dataparams:
  path_to_data: "./data/raw/data.txt"
  file_format: "tsv"
  split_ratio: [0.8, 0.15, 0.05]
  min_word_freq: 3
  batch_size: 128
seq2seqparams:
  enc_emb_dim: 128
  dec_emb_dim: 128
  enc_hid_dim: 256
  dec_hid_dim: 256
  enc_dropout: 0.15
  dec_dropout: 0.15
  n_layers: 2
  save_path: "./src/models/baseline.pt"
trainparams:
  clip: 1
  num_epochs: 5
  teacher_forcing_ratio: 0.35
  translated_examples_file: "./reports/baseline_translated_exams.log"
